x-logging: &default-logging
    driver: loki
    options:
        loki-url: "http://localhost:3100/api/prom/push"
        loki-pipeline-stages: |
            - multiline:
                firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
                max_wait_time: 3s
            - regex:
                expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}) (?P<message>(?s:.*))$$'

services:
    engine:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        env_file:
            - ./../.env
        deploy:
            replicas: 1
        # Do not open port at Production
        ports:
            - "8080:8000"
        volumes:
            - ./src/:/zkit/
        networks:
            - zkit_network
        #depends_on:
        #    - postgres
        restart: unless-stopped
        logging: *default-logging
