services:
    engine:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - PYTHON_VERSION=${PYTHON_VERSION}
        env_file:
            - ./../.env
        deploy:
            replicas: 1
        # Do not open port at Production
        ports:
            - "8080:8000"
        volumes:
            - ./src/:/zkit/
        networks:
            - zkit_network
        depends_on:
            - postgres
        restart: unless-stopped
