ITEM_NOT_FOUND = "Item not found"
ITEM_ALREADY_EXISTS = "Item already exists"
CREATE_FAILED = "Create failed"
CREATE_SUCCEED = "Create succeed"
UPDATE_FAILED = "Update failed"
UPDATE_SUCCEED = "Update succeed"
DELETE_FAILED = "Delete failed"
DELETE_SUCCEED = "Delete succeed"
